version: '3.8'

services:
  server:
    build:
      context: .
    container_name: meli-app
    # command: npm run dev
    # ports:
    #   - 3000:3000
    #   - 3001:3001
    # networks:
    #   - myNetwork
    # environment:
    #   NODE_ENV: development

# networks:
#   myNetwork:
#     # Use a custom driver
#     driver: bridge