version: '3.8'

services:
  server:
    build:
      context: ./server-api/.
    container_name: server-api
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - ALLOW_ORIGIN=["http://localhost:3001" , "http://127.0.0.1:3001"]

  client:
    build:
      context: ./web-client/.
      args: 
        - SERVER_URL_BASE=http://localhost:3000/api/v1/
    container_name: web-client
    command: npm run dev
    ports:
      - 3001:3001
